language: python
python:
    - "2.7"
before_install:
    - pip install -r requirements.txt
    - pip install --upgrade pytest
    - pip install pytest pytest-cov pytest-django model-mommy pytest-pep8
script:
    - py.test --pep8