version: '2'
services:
  app:
    image: nalch/basicdeauth:0.7
    environment:
      - STAGE=p
    volumes:
      - nginx_html:/var/www/html
      - basicdeauth_conf_path:/etc/local/basicdeauth/conf
      - basicdeauth_var_path:/var/local/basicdeauth
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      default: {}
      nginx-net: {}
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB=basicdeauth
      - POSTGRES_USER=basicdeauth
      - POSTGRES_PASSWORD=basicdeauth
      - PGDATA=/var/local/basicdeauth/pgdata
    volumes:
      - basicdeauth_var_path:/var/local/basicdeauth
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3

volumes:
  basicdeauth_app_path:
    external: true
  basicdeauth_var_path:
    external: true
  nginx_html:
    external: true
  basicdeauth_conf_path:
    external: true

networks:
  nginx-net:
    external:
      name: nginx-net