version: '2'
services:
  app:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8100
    ports:
      - "8600:8100"
    environment:
      - STAGE=dev
    volumes:
      - .:/usr/src/app
      - ./static:/var/www/html
      - ./config:/etc/local/basicdeauth/conf
      - ./var:/var/local/basicdeauth
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB=basicdeauth
      - POSTGRES_USER=basicdeauth
      - POSTGRES_PASSWORD=basicdeauth
      - PGDATA=/var/local/basicdeauth/pgdata
    volumes:
      - ./var:/var/local/basicdeauth